# Generated by Django 5.1.7 on 2026-06-09 08:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('container_no', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_date', models.CharField(blank=True, max_length=50, null=True)),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('nzd', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('paid_by', models.CharField(blank=True, max_length=100)),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('cash_in', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True)),
                ('cash_out', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='containers.container')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory_List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('in_stock_qty', models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_sold_qty', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='containers.container')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'indexes': [models.Index(fields=['code'], name='containers__code_5f60cc_idx'), models.Index(fields=['product_name'], name='containers__product_15c25e_idx')],
            },
        ),
    ]
