# Generated by Django 5.1.7 on 2026-02-26 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='pending', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='sale_status',
            field=models.CharField(blank=True, choices=[('in_store', 'In Store'), ('sold_to_company', 'Sold to Company'), ('sold_to_customer', 'Sold to Customer')], default='in_store', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='container',
            name='total_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='total_sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='transport_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('in_stock', 'In Stock')], default='pending', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='containertransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory_list',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='inventory_list',
            name='qty_sold',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='inventory_list',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('partial', 'Partial'), ('sold_out', 'Sold Out')], default='available', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventory_list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
