# Generated by Django 5.1.7 on 2026-02-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_container_arrival_date_container_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
