# Generated by Django 5.1.7 on 2026-07-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_expensecategory_expense'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='containers__content_b05742_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='object_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='containers.container'),
        ),
    ]
