# Generated by Django 5.1.7 on 2026-06-09 08:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_type', models.CharField(choices=[('employee', ' کارمند'), ('saraf', ' صراف')], max_length=20, verbose_name='نوع شخص')),
                ('status', models.CharField(choices=[('active', ' فعال'), ('inactive', ' غیرفعال')], default='active', max_length=20, verbose_name='وضعیت')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مانده حساب')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حقوق')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='دپارتمان')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='شماره مجوز')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد کمیسیون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['person_type'], name='employee_pe_person__12b127_idx'), models.Index(fields=['name'], name='employee_pe_name_1b5f42_idx')],
            },
        ),
        migrations.CreateModel(
            name='SarafTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(blank=True, max_length=150, verbose_name='روز')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, verbose_name='شرح تراکنش')),
                ('paid_by', models.CharField(blank=True, max_length=150, verbose_name='پرداخت کننده')),
                ('received_by', models.CharField(blank=True, max_length=150, verbose_name='دریافت کننده')),
                ('category', models.CharField(choices=[('buy', 'خرید ارز'), ('sell', 'فروش ارز')], default='other', max_length=50, verbose_name='دسته\u200cبندی')),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ورودی')),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='خروجی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('saraf', models.ForeignKey(blank=True, limit_choices_to={'person_type': 'saraf'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='employee.person', verbose_name='صراف')),
            ],
            options={
                'verbose_name': 'تراکنش صرافی',
                'verbose_name_plural': 'تراکنش\u200cهای صرافی',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='employee_sa_date_c7fa00_idx'), models.Index(fields=['category'], name='employee_sa_categor_c94463_idx')],
            },
        ),
    ]
