# Generated by Django 5.1.7 on 2026-07-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saraftransaction',
            name='nzd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='مبلغ NZD'),
        ),
        migrations.AddField(
            model_name='saraftransaction',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='نرخ تبدیل'),
        ),
        migrations.AddField(
            model_name='saraftransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='مرجع'),
        ),
        migrations.AlterField(
            model_name='saraftransaction',
            name='category',
            field=models.CharField(choices=[('salary', 'حقوق'), ('deposit', 'واریز'), ('loan', 'وام'), ('payment', 'پرداخت'), ('transfer', 'انتقال'), ('buy_currency', 'خرید ارز'), ('sell_currency', 'فروش ارز'), ('other', 'سایر')], default='other', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='saraftransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saraftransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
