# Generated by Django 5.1.7 on 2026-07-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_saraftransaction_nzd_amount_saraftransaction_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saraftransaction',
            name='nzd_amount',
        ),
        migrations.RemoveField(
            model_name='saraftransaction',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='saraftransaction',
            name='reference',
        ),
        migrations.AddField(
            model_name='person',
            name='saraf_shop_address',
            field=models.TextField(blank=True, verbose_name='آدرس مغازه'),
        ),
        migrations.AddField(
            model_name='person',
            name='saraf_shop_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام مغازه'),
        ),
        migrations.AlterField(
            model_name='saraftransaction',
            name='category',
            field=models.CharField(choices=[('buy', 'خرید ارز'), ('sell', 'فروش ارز')], default='other', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='saraftransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='saraftransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
