# Generated by Django 5.1.7 on 2026-07-01 15:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_saraftransaction_nzd_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='saraf_shop_address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='saraf_shop_name',
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('saraf', 'Money Changer')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PersonTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('paid_by', models.CharField(blank=True, max_length=150)),
                ('received_by', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('deposit', 'Deposit'), ('loan', 'Loan'), ('payment', 'Payment'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=50)),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='employee.person')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SarafTransaction',
        ),
        migrations.AddIndex(
            model_name='persontransaction',
            index=models.Index(fields=['person', 'date'], name='employee_pe_person__98bc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='persontransaction',
            index=models.Index(fields=['category'], name='employee_pe_categor_731840_idx'),
        ),
    ]
