# Generated by Django 5.1.7 on 2026-07-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_person_options_remove_person_commission_rate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='employee_pe_person__12b127_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='employee_pe_name_1b5f42_idx',
        ),
        migrations.RemoveIndex(
            model_name='persontransaction',
            name='employee_pe_person__98bc8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='persontransaction',
            name='employee_pe_categor_731840_idx',
        ),
    ]
