# Generated by Django 5.1.7 on 2026-06-09 08:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('container_no', models.CharField(blank=True, max_length=100, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_qty', models.IntegerField(default=0)),
                ('transaction_count', models.IntegerField(default=0)),
                ('not_sold', models.IntegerField(default=0)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('item_id', models.UUIDField(blank=True, null=True)),
                ('container_id', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'code'],
                'indexes': [models.Index(fields=['date'], name='daily_sale__date_4a158a_idx'), models.Index(fields=['code'], name='daily_sale__code_1f9b2a_idx')],
                'unique_together': {('date', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DailySaleTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_description', models.CharField(blank=True, max_length=500, null=True)),
                ('qty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sales', to='containers.container')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sales', to='containers.inventory_list')),
            ],
            options={
                'db_table': 'daily_sale_transaction',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='daily_sale__date_130dc8_idx'), models.Index(fields=['invoice_number'], name='daily_sale__invoice_55e88a_idx'), models.Index(fields=['customer_name'], name='daily_sale__custome_255e4e_idx'), models.Index(fields=['code'], name='daily_sale__code_aebeb9_idx'), models.Index(fields=['item'], name='daily_sale__item_id_06742b_idx'), models.Index(fields=['container'], name='daily_sale__contain_4327ec_idx')],
            },
        ),
    ]
