# Generated by Django 5.1.7 on 2026-02-27 10:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
    ]
