# Generated by Django 5.1.7 on 2026-06-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0001_initial'),
    ]

    operations = [
    ]
