# Generated by Django 5.1.7 on 2026-07-03 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0002_auto_20260627_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='qty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
